<h3 class="page-header">
    Try commenting created Test Entity.
</h3>
<div id="grid">
    <div class="head row">
        <div class="col-md-1">id</div>
        <div class="col-md-2">email</div>
        <div class="col-md-2">name</div>
        <div class="col-md-3"></div>
        <hr/>
    </div>
    <div class="row entity" >
        <div class="col-md-1">
            <strong><?= $testEntity->getId() ?></strong>
        </div>
        <div class="col-md-2">
            <strong><?= $testEntity->getEmail() ?></strong>
        </div>
        <div class="col-md-2">
            <strong><?= $testEntity->getName() ?></strong>
        </div>
        <div class="col-md-6">
            <?php if (null !== $addCommentForm) : ?>
                <?= $addCommentForm ?>
            <?php endif; ?>
        </div>
    </div>
</div>
<div data-spy="grid"  data-url="<?= $this->url('test/default', ['controller' => 'comment', 'action' => 'index'])?>">
    <div class="grid">
        <?php if ($comments && $isVisible !== 0) {
            echo $this->comment('comment/index/partial/comment.phtml', $comments);
        }; ?>
    </div>
</div>

<script>
    require(['dashboard', 'test', 'comment']);
</script>