<h3 class="page-header">
    Try commenting created Test Entity.
</h3>
<div id="grid">
    <div class="head row">
        <div class="col-md-1">id</div>
        <div class="col-md-2">email</div>
        <div class="col-md-2">name</div>
        <div class="col-md-3"></div>
        <hr/>
    </div>
    <?php foreach ($this->data as $row) : ?>
        <div class="row entity"  data-href="<?= $this->url('comment/default', ['controller' => 'index', 'action' => 'index'], ['query' => ['entity' => $this->aliasEntity,'id' => $row->getId()]]) ?>">
            <div class="col-md-1">
                <strong><?= $row->getId() ?></strong>
            </div>
            <div class="col-md-2">
                <strong><?= $row->getEmail() ?></strong>
            </div>
            <div class="col-md-2">
                <strong><?= $row->getName() ?></strong>
            </div>
            <?php if ($this->enabledComment) : ?>
                <div class="col-md-6">
                    <?php if ($this->enabledComment) : ?>
                        <div class="add-comment-form col-md-4"><?php $commentService->generateAddCommentForm($commentService->createForm()); ?></div>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        </div>
        <div class="row"></div>
    <?php endforeach; ?>
</div>

<script>
    require(['test','comment', 'fury.form', 'dashboard']);
</script>