<?php
$form = $this->form;
$form->setAttribute('action', $this->url('user', ['action' => 'settings', 'id' => $this->id]));
$form->prepare();
?>
<div class="container"></div>
<form role="form" class="form-horizontal" method="post">

    <?php if ($this->currentPasswordElement):?>
        <div class="form-group">
            <label for="inputCurrentPassword"
                   class="col-md-2 control-label"><?= $this->escapeHtml($form->get('currentPassword')->getLabel()); ?></label>
            <div class="col-md-4">
                <input type="password" class="form-control" id="inputCurrentPassword"
                       name="<?= $this->escapeHtml($form->get('currentPassword')->getName()); ?>"
                       placeholder="<?= $this->escapeHtml($form->get('currentPassword')->getLabel()); ?>">
                <?= $this->formElementErrors($form->get('currentPassword')); ?>
            </div>
        </div>
    <?php else :?>
        <div class="form-group">
            <label for="inputEmail"
                   class="col-md-2 control-label"><?= $this->escapeHtml($form->get('email')->getLabel()); ?></label>
            <div class="col-md-4">
                <input type="email" class="form-control" id="inputEmail"
                       name="<?= $this->escapeHtml($form->get('email')->getName()); ?>"
                       placeholder="<?= $this->escapeHtml($form->get('email')->getLabel()); ?>">
                <?= $this->formElementErrors($form->get('email')); ?>
            </div>
        </div>
    <?php endif ;?>

    <div class="form-group">
        <label for="inputNewPassword"
               class="col-md-2 control-label"><?= $this->escapeHtml($form->get('password')->getLabel()); ?></label>

        <div class="col-md-4">
            <input type="password" class="form-control" id="inputNewPassword"
                   name="<?= $this->escapeHtml($form->get('password')->getName()); ?>"
                   placeholder="<?= $this->escapeHtml($form->get('password')->getLabel()); ?>">
            <?= $this->formElementErrors($form->get('password')); ?>
        </div>
    </div>
    <div class="form-group">
        <label for="inputConfirmNewPassword"
               class="col-md-2 control-label"><?= $form->get('repeat-password')->getLabel(); ?></label>

        <div class="col-md-4">
            <input type="password" class="form-control" id="inputConfirmNewPassword"
                   name="<?= $form->get('repeat-password')->getName(); ?>"
                   placeholder="<?= $form->get('repeat-password')->getLabel(); ?>">
            <?= $this->formElementErrors($form->get('repeat-password')); ?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-4">
            <button class="btn btn-primary" type="submit">Submit changes</button>
        </div>
    </div>
</form>
<script>
    require(['fury']);
</script>