<?php
$form = $this->form;
$form->setAttribute('action', $this->url('user', ['action' => 'settings', 'id' => $this->id]));
$form->prepare();
?>
<div class="container"></div>
<form role="form" class="form-horizontal" method="post">
    <div class="form-group">
        <label for="inputCurrentPassword" class="col-md-2 control-label"><?= $this->escapeHtml($form->get('currentPassword')->getLabel()); ?></label>
        <div class="col-md-4">
            <input type="password" class="form-control" id="inputCurrentPassword" name="<?= $this->escapeHtml($form->get('currentPassword')->getName()); ?>" placeholder="<?= $this->escapeHtml($form->get('currentPassword')->getLabel()); ?>">
            <?= $this->formElementErrors($form->get('currentPassword')); ?>
        </div>
    </div>
    <div class="form-group">
        <label for="inputNewPassword" class="col-md-2 control-label"><?= $this->escapeHtml($form->get('newPassword')->getLabel()); ?></label>
        <div class="col-md-4">
            <input type="password" class="form-control" id="inputNewPassword" name="<?= $this->escapeHtml($form->get('newPassword')->getName()); ?>" placeholder="<?= $this->escapeHtml($form->get('newPassword')->getLabel()); ?>">
            <?= $this->formElementErrors($form->get('newPassword')); ?>
        </div>
    </div>
    <div class="form-group">
        <label for="inputConfirmNewPassword" class="col-md-2 control-label"><?= $form->get('newPasswordConfirm')->getLabel(); ?></label>
        <div class="col-md-4">
            <input type="password" class="form-control" id="inputConfirmNewPassword" name="<?= $form->get('newPasswordConfirm')->getName(); ?>" placeholder="<?= $form->get('newPasswordConfirm')->getLabel(); ?>">
            <?= $this->formElementErrors($form->get('newPasswordConfirm')); ?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-4">
            <button class="btn btn-primary" type="submit">Submit changes</button>
        </div>
    </div>

</form>