<div>
    <h3>IDs</h3>
    <ul>
        <?php foreach ($imagesId as $imageId) { ?>
            <li>Image ID: <?= $imageId ?></li>
        <?php } ?>
    </ul>
</div>
<div>
    <h3>URLs of an original</h3>
    <ul>
        <?php foreach ($imagesUrl as $imageUrl) { ?>
            <li>Original URL: <?= $imageUrl ?></li>
        <?php } ?>
    </ul>
</div>
<div>
    <h3>URLs of a thumb</h3>
    <ul>
        <?php foreach ($thumbsUrl as $thumbUrl) { ?>
            <li>Thumbnail URL: <?= $thumbUrl ?></li>
        <?php } ?>
    </ul>
</div>
<div>
    <h3>Location of an original (from project-root)</h3>
    <ul>
        <?php foreach ($imagesLocation as $imageLocation) { ?>
            <li>Location: <?= $imageLocation ?></li>
        <?php } ?>
    </ul>
</div>
