language: php
php:
  - 5.4
before_install:
  - chmod +x travis.config.sh
  - chmod +x install.sh
install:
  # Database
  - mysql -e 'CREATE DATABASE IF NOT EXISTS p_zfury_test;' -uroot
  # Composer install, .htaccsess, directories, rights
  - ./install.sh
  # Configs
  - ./travis.config.sh
script:
  # Unit tests
  - ./vendor/bin/phpunit -c tests/phpunit.xml --coverage-clover 'logs/phpunit.clover.xml'
  # Code style
  #- ./vendor/bin/phpcs module/ --tab-width=4 --report=checkstyle --standard=PSR2 --extensions=php --ignore=js --report-file=logs/phpcs.xml --encoding=utf-8 > logs/phpcs.log
  # Code Browser
  #- ./vendor/bin/phpcb --log logs/ --source module/ --output logs/phpcb
  #- zip -r logs/phpcb.zip logs/phpcb
after_script:
  # Zipping coverage
  - php vendor/bin/coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover logs/phpunit.clover.xml; fi;'
notifications:
  email: false
