<?php
/**@var $form Zend/Form */
$form = $this->form;
?>
<div class="container">
    <h1><?php echo $this->escapeHtml($this->title); ?></h1>

    <div class="row">
        <form action="" method="post" class="form-horizontal" id="newCategory">
            <?php foreach ($this->form->getElements() as $element) : ?>
                <?php
                $formElement = $this->formInput($element);
//            var_dump($element->getAttributes()['type']);die();
//                switch ($element) {
//                    case $element instanceof Zend\Form\Element\Select :
//                        $formElement = $this->formSelect($element);
//                        break;
//                    case $element instanceof Zend\Form\Element\Email :
//                        $formElement = $this->formEmail($element);
//                        break;
//                    case $element instanceof Zend\Form\Element\Password :
//                        $formElement = $this->formPassword($element);
//                        break;
//                    default :
//                        $formElement = $this->formInput($element);
//                        break;
//                }
                ?>
                <div class="form-group">
                    <?php if ($element->getAttributes()['type'] !== 'hidden'): ?>
                        <label for="<?= $element->getName(); ?>" class="col-sm-2 control-label">
                            <?= $element->getLabel() ? $element->getLabel() : ucfirst($element->getName()); ?>
                        </label>
                    <?php endif; ?>
                    <div class="col-sm-4">
                        <?= $formElement; ?>
                    </div>
                    <?= $this->formElementErrors($element); ?>
                </div>
            <?php endforeach; ?>
            <div class="form-group">
                <div class="col-sm-2"></div>
                <div class="col-sm-4">
                    <input type="submit" name="submit" class="btn btn-lg btn-primary btn-block" value="Save">
                </div>
            </div>
        </form>
    </div>
</div>