<?php
/**@var $form Zend\Form\Form */
$form = $this->form;
$scripts = isset($this->scripts) ? $this->scripts : [];
$ajax = $this->viewModel()->getCurrent()->terminate();
?>
    <div class="container form-container">
        <input type="hidden" id="entityId" value="<?= $this->fileUpload['id'] ? $this->fileUpload['id'] : ''; ?>">
        <br>

        <div class="col-md-8 form-center col-md-offset-4">
            <?php if (!$ajax): ?>
                <h1 class="create-label"><?= !$this->title ? 'Create' : $this->escapeHtml($this->title); ?></h1>
            <?php endif; ?>
            <form action="<?= $form->getAttribute('action') ?>" method="post" class="form-horizontal <?= $ajax ? 'form-ajax' : '' ?>">
                <?php foreach ($form->getElements() as $element) : ?>
                    <?php
                    switch ($element) {
                        case $element instanceof Zend\Form\Element\Select :
                            $formElement = $this->formSelect($element);
                            break;
                        case $element instanceof Zend\Form\Element\Email :
                            $formElement = $this->formEmail($element);
                            break;
                        case $element instanceof Zend\Form\Element\Password :
                            $formElement = $this->formPassword($element);
                            break;
                        case $element instanceof \Fury\Form\Element\Redactor :
                            array_push($scripts, 'redactorContent');
                            $formElement = $this->formTextarea($element);
                            break;
                        case $element instanceof Zend\Form\Element\Textarea :
                            $formElement = $this->formTextarea($element);
                            break;
                        case $element instanceof Zend\Form\Element\Hidden :
                            $formElement = $this->formHidden($element);
                            break;
                        default :
                            $formElement = $this->formInput($element);
                            break;
                    }
                    ?>
                    <?php $element->getAttributes()['type'] == 'submit' ? $submit = true : $submit = false; ?>
                    <div class="form-group">
                        <?php if (!$submit): ?>
                            <?php if ($element->getAttributes()['type'] !== 'hidden'): ?>
                                <label for="<?= $element->getName(); ?>" class="col-sm-2 control-label">
                                    <?= $element->getLabel() ? $element->getLabel() : ucfirst($element->getName()); ?>
                                </label>
                            <?php endif; ?>
                            <div class="col-sm-9">
                                <?= $formElement; ?>
                                <div class="error-field error-form-message">
                                    <?= $this->formElementErrors($element); ?>
                                </div>
                            </div>
                        <?php else: ?>
                            <?php if (!$ajax): ?>
                                <div class="col-sm-9 col-sm-offset-2">
                                    <?= $formElement; ?>
                                    <div class="error-field error-form-message">
                                        <?= $this->formElementErrors($element); ?>
                                    </div>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>
                <?php if (!$submit && !$ajax): ?>
                    <div class="form-group">
                        <div class="col-sm-9 col-sm-offset-2">
                            <input type="submit" name="submit" class="form-control col-md-6 btn btn-success"
                                   value="<?= $this->title == 'Edit' ? 'Save' : 'Create'; ?>">
                        </div>
                    </div>
                <?php endif; ?>
            </form>
            <div class="col-sm-10 col-sm-offset-2">
                <?php if ($this->fileUpload): ?>
                    <?php
                    echo $this->fileUpload['imageService']->generateFileUploadForm($this->fileUpload['type']);
                    ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
<?php if (!$ajax): ?>
    <script>
        require(['dashboard', 'categories', 'image-categories']);
    </script>
<?php endif; ?>