<?= $this->headLink()->appendStylesheet($this->basePath() . '/redactor/redactor.css'); ?>
<?php
/**@var $form Zend\Form\Form */
$form = $this->form;
$scripts = $this->scripts ? $this->scripts : [];
$ajax = $this->ajax ? $this->ajax : false;
?>
<div class="container form-container">
    <input type="hidden" id="entityId" value="<?= $this->fileUpload['id'] ? $this->fileUpload['id'] : ''; ?>">
    <br>

    <div class="col-md-8 form-center col-md-offset-4">
        <?php if (!$ajax): ?>
            <h1 class="create-label"><?= !$this->title ? 'Create' : $this->escapeHtml($this->title); ?></h1>
        <?php endif; ?>
        <form action="" method="post" class="form-horizontal" id="crudForm">
            <?php foreach ($form->getElements() as $element) : ?>
                <?php
                switch ($element) {
                    case $element instanceof Zend\Form\Element\Select :
                        $formElement = $this->formSelect($element);
                        break;
                    case $element instanceof Zend\Form\Element\Email :
                        $formElement = $this->formEmail($element);
                        break;
                    case $element instanceof Zend\Form\Element\Password :
                        $formElement = $this->formPassword($element);
                        break;
                    case $element instanceof \Starter\Form\Element\Redactor :
                        array_push($scripts, 'redactorContent');
                        $formElement = $this->formTextarea($element);
                        break;
                    case $element instanceof Zend\Form\Element\Textarea :
                        $formElement = $this->formTextarea($element);
                        break;
                    case $element instanceof Zend\Form\Element\Hidden :
                        $formElement = $this->formHidden($element);
                        break;
                    default :
                        $formElement = $this->formInput($element);
                        break;
                }
                ?>
                <?php $element->getAttributes()['type'] == 'submit' ? $submit = true : $submit = false; ?>
                <div class="form-group">
                    <?php if ($element->getAttributes()['type'] !== 'submit'): ?>
                        <?php if ($element->getAttributes()['type'] !== 'hidden'): ?>
                            <label for="<?= $element->getName(); ?>" class="col-sm-2 control-label">
                                <?= $element->getLabel() ? $element->getLabel() : ucfirst($element->getName()); ?>
                            </label>
                        <?php endif; ?>
                    <?php else: ?>
                        <div class="col-sm-2"></div>
                    <?php endif; ?>
                    <div class="col-sm-9">
                        <?= $formElement; ?>
                    </div>
                    <div class="col-sm-9 col-sm-offset-2 error-field error-form-message">
                        <?= $this->formElementErrors($element); ?>
                    </div>
                </div>
            <?php endforeach; ?>
            <?php if (!$submit && !$ajax): ?>
                <div class="form-group">
                    <div class="col-sm-9 col-sm-offset-2">
                        <input type="submit" name="submit" class="form-control col-md-6 btn btn-success"
                               value="<?= $this->title == 'Edit' ? 'Save' : 'Create'; ?>">
                    </div>
                </div>
            <?php endif; ?>
        </form>
        <div class="col-sm-10 col-sm-offset-2">
            <?php if ($this->fileUpload): ?>
                <?php
                echo $this->fileUpload['imageService']->generateFileUploadForm($this->fileUpload['type']);
                ?>
            <?php endif; ?>
        </div>
    </div>

</div>
<script>
    require([
        <?= implode(',', array_map(function($a) { return "'$a'"; }, $scripts));?>
    ]);
</script>