<div id="dialog">
</div>
<div class="category-page-wrapper">
    <nav class="navbar navbar-default" role="navigation">
        <div class="form-group">
            <div class="col-lg-1">
                <a href="#"
                   class="btn btn-success navbar-btn dialog addAjax"
                   data-toggle="modal"
                   data-target="#myModal"
                   data-url="<?= $this->url('categories/create') ?>"
                   data-action="Create category"
                   data-ajax-method=" get"><?php echo $this->translate('Create category') ?></a>
            </div>
            <div class="col-lg-5">
                <a href="<?php echo $this->url('categories/default'); ?>"
                   class="btn btn-primary navbar-btn hidden create-child">
                    <?php echo $this->translate('Add child'); ?></a>
            </div>
            <div class="col-lg-6 select-tree">
                <form action="<?php echo $this->url('categories/default'); ?>" class="form-horizontal">
                    <select class="form-control root-category-list">
                        <?php if (isset($this->rootTree) && $this->rootTree): ?>
                            <?php foreach ($this->rootTree as $tree): ?>
                                <option <?php if ($tree->getId() == $currentRoot->getId()) echo 'selected'; ?>
                                    value="<?php echo $tree->getId() ?>"><?php echo $tree->getName() ?></option>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </select>
                </form>
            </div>
        </div>
    </nav>

    <div class="tree-container">
        <div class="tree-wrapper">
            <?php if (isset($currentRoot) && $currentRoot): ?>
                <div class="tree-header well well-sm"
                     data-parent-id="<?= $currentRoot->getId(); ?>"><?= $currentRoot->getName(); ?>
                    <div class="pull-right">
                        <a href="#"
                           class="btn btn-xs btn-success addAjax"
                           data-toggle="modal"
                           data-target="#myModal"
                           id="addAjax"
                           data-url="<?= $this->url('categories/create', array('parentId' => $currentRoot->getId())) ?>"
                           data-action="Create category">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                        </a>
                        <a href="#"
                           class="btn btn-primary btn-xs addAjax"
                           data-toggle="modal"
                           data-target="#myModal"
                           data-url="<?= $this->url('categories/default', array('controller' => 'management', 'action' => 'edit', 'id' => $currentRoot->getId())) ?>"
                           data-action="Edit category">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                        </a>
                        <a href="<?= $this->url('categories/default', array('controller' => 'management', 'action' => 'delete', 'id' => $currentRoot->getId())) ?>"
                           class="btn btn-xs btn-danger delete-category">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        </a>
                    </div>
                </div>
            <?php endif; ?>

            <?php if (isset($categories) && $categories): ?>
                <div class="sortable-wrapper">
                    <ol class="sortable">
                        <?php echo $this->treeBuild($categories); ?>
                    </ol>
                </div>
                <hr/>
                <button id="save" class="btn btn-primary"><?= $this->translate('Save') ?></button>
            <?php endif; ?>
        </div>
    </div>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel"></h4>
            </div>
            <div class="modal-body" id="popupBody">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="close-form-button" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="submit-form-button">Save</button>
            </div>
        </div>
    </div>
</div>
<script>
    require(['frontend', 'categories']);
</script>