<h2>Categories</h2>
<div class="category-page-wrapper">
    <nav class="navbar navbar-default" role="navigation">
        <div class="form-group">
            <div class="col-lg-1">
                <a href="<?= $this->url('categories/create') ?>"
                   class="btn btn-success navbar-btn dialog"
                   data-title="Create category"><?php echo $this->translate('Create category') ?></a>
            </div>
            <div class="col-lg-5">
                <a href="<?php echo $this->url('categories/default'); ?>"
                   class="btn btn-primary navbar-btn hidden create-child">
                    <?php echo $this->translate('Add child'); ?></a>
            </div>
            <div class="col-lg-6 select-tree">
                <form action="<?php echo $this->url('categories/default'); ?>" class="form-horizontal">
                    <select class="form-control root-category-list">
                        <?php if (isset($this->rootTree) && $this->rootTree): ?>
                            <?php foreach ($this->rootTree as $tree): ?>
                                <option <?php if ($tree->getId() == $currentRoot->getId()) echo 'selected'; ?>
                                    value="<?php echo $tree->getId() ?>"><?php echo $tree->getName() ?></option>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </select>
                </form>
            </div>
        </div>
    </nav>

    <div class="tree-container">
        <div class="tree-wrapper">
            <?php if (isset($currentRoot) && $currentRoot): ?>
                <div class="tree-header well well-sm"
                     data-parent-id="<?= $currentRoot->getId(); ?>">
                    <img src="<?= $currentRoot->getImageUrl(); ?>">
                    <?= $currentRoot->getName(); ?>
                    <div class="pull-right">
                        <a href="<?= $this->url('categories/create', array('parentId' => $currentRoot->getId())) ?>"
                           class="btn btn-xs btn-success dialog"
                           data-title="Create category">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                        </a>
                        <a href="<?= $this->url('categories/default', array('controller' => 'management', 'action' => 'edit', 'id' => $currentRoot->getId())) ?>"
                           class="btn btn-primary btn-xs dialog"
                           data-title="Edit category">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                        </a>
                        <a href="<?= $this->url('categories/default', array('controller' => 'management', 'action' => 'delete', 'id' => $currentRoot->getId())) ?>"
                           class="btn btn-xs btn-danger delete-entity">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        </a>
                    </div>
                </div>
            <?php endif; ?>

            <?php if (isset($categories) && $categories): ?>
                <div class="sortable-wrapper">
                    <ol class="sortable">
                        <?php echo $this->treeBuild($categories); ?>
                    </ol>
                </div>
                <hr/>
                <button id="save" class="btn btn-primary"><?= $this->translate('Save') ?></button>
            <?php endif; ?>
        </div>
    </div>
</div>
<script>
    require(['dashboard', 'categories', 'image-categories']);
</script>