<?php
/**
 * Created by PhpStorm.
 * User: babich
 * Date: 25.11.14
 * Time: 12:06
 */
?>
<div class="well well-sm">
    <img src="<?= $this->node->getImageUrl(); ?>">
    <?= $this->escapeHtml(($this->node->getName())) ?>
    <div class="pull-right">
        <a href="<?= $this->url('categories/create', array('parentId' => $this->node->getId())) ?>"
           class="btn btn-xs btn-success dialog"
           data-title="Create category"
           data-ajax-method="get">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        </a>
        <a href="<?= $this->url('categories/default', array('controller' => 'management', 'action' => 'edit', 'id' => $this->node->getId())) ?>"
           class="btn btn-primary btn-xs dialog"
           data-title="Edit category"
           data-ajax-method="get">
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
        </a>
        <a href="<?= $this->url('categories/default', array('controller' => 'management', 'action' => 'delete', 'id' => $this->node->getId())) ?>"
           class="btn btn-xs btn-danger ajax confirm"
           data-ajax-method="delete">
            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
        </a>
    </div>
</div>