<?php
$title = 'Requirements';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<form role="form" action="<?=$this->url('install/default', ['controller' => 'index', 'action' => 'requirements'])?>" class="form-horizontal" method="post">
    <?php
    if (isset($requirements)) {
    ?>
    <ul>
    <?php  foreach (array_keys($requirements) as $moduleName) {?>
        <li>
            <h4>For module <?=$moduleName?></h4>
            <dl class="dl-horizontal">
                <?php for ($i=0; $i<count($requirements[$moduleName]); $i++) {?>
                <dt><?=array_keys($requirements[$moduleName])[$i]?></dt>
                <dd><?=array_values($requirements[$moduleName])[$i]?></dd>
                <?php } ?>
            </dl>
        </li>
    <?php } ?>
    </ul>
    <?php } ?>
    <div class="form-group">
        <div class="col-md-offset-2 col-sm-3">
            <div class="btn btn-primary"><a href="<?=$this->url('install/default', ['controller' => 'index', 'action' => 'modules'])?>">Previous</a></div>
        </div>
        <div class="col-sm-2">
            <button class="btn btn-primary" type="submit">Save</button>
        </div>
    </div>
</form>