<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                <li><a href="<?php echo $this->url('user/default', ['controller' => 'signup', 'action' => 'index']) ?>"><?php echo $this->translate('Signup') ?></a></li>
                <?php if (!$this->identity()) : ?>
                    <li><a href="<?php echo $this->url('user/default', ['controller' => 'auth', 'action' => 'login']) ?>"><?php echo $this->translate('Login') ?></a></li>
                <?php endif; ?>
                <?php if ($this->identity() && \User\Entity\User::ROLE_ADMIN == $this->identity()->getUser()->getRole()) : ?>
                    <li><a href="<?php echo $this->url('dashboard', ['controller' => 'index', 'action' => 'index']) ?>"><?php echo $this->translate('Dashboard') ?></a></li>
                    <li><a href="<?php echo $this->url('options/default') ?>"><?php echo $this->translate('Options') ?></a></li>
                    <li><a href="<?php echo $this->url('categories/default', array('controller' => 'management', 'action' => 'index')) ?>"><?php echo $this->translate('Categories') ?></a></li>
                <?php endif; ?>
                <li><a href="<?php echo $this->url('test/default', ['controller' => 'management', 'action' => 'index']) ?>"><?php echo $this->translate('Test') ?></a></li>
            </ul>
            <?php if ($this->identity()) : ?>
                <p class="navbar-text navbar-right">
                    Logged in as <a href="<?php echo $this->url('user/default', ['controller' => 'profile']) ?>" class="on"><?= $this->identity()->getUser()->getEmail() ? $this->identity()->getUser()->getEmail() : $this->identity()->getUser()->getDisplayName(); ?></a>
                    (<a href="<?php echo $this->url('user/default', ['controller' => 'auth', 'action' => 'logout']) ?>"><?php echo $this->translate('Logout') ?></a>)
                </p>
            <?php endif; ?>
        </div><!--/.nav-collapse -->
    </div>
</nav>