<?php
/**
 * Created by PhpStorm.
 * User: babich
 * Date: 12/9/14
 * Time: 4:34 PM
 */

echo $this->partial('layout/crud/create.phtml',
    [
        'form' => $this->form,
        'title' => 'Edit',
        'scripts' => $this->scripts ? $this->scripts : null,
        'imageUploadForm' => $this->imageUploadForm,
        'imageService' => $this->imageService,
        'module' => $this->module,
        'id' => $this->id ? $this->id : null
    ]
);