<?php
$title = '';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.0/css/font-awesome.css" rel="stylesheet">
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
    ->prependStylesheet($this->basePath() . '/css/bootstrap-social.css') ?>
<?php
/**
 * @var Zend/Form/Form $form
 */
$form = $this->form;
$form->setAttribute('action', $this->url('user/default', array('controller' => 'auth', 'action' => 'login')));
$form->setAttribute('class', 'form-signin');
$form->prepare();
?>
<div class="container text-center">
        <?php echo $this->form()->openTag($form); ?>
        <?php echo $this->formHidden($form->get('security')); ?>
    <h2 class="form-signin-heading">Sign in</h2>
    <p>
        <?php if (isset($this->serviceLocator->get('config')['facebook'])): ?>
            <a class="btn social-login-btn social-facebook btn-facebook"  href="<?php echo $this->url('user/default', ['controller' => 'auth', 'action' => 'facebook']) ?>"
                ><i class="fa fa-facebook"></i>
            </a>
        <?php endif; ?>
        <?php if (isset($this->serviceLocator->get('config')['twitter'])): ?>
            <a class="btn social-login-btn social-twitter btn-twitter" href="<?php echo $this->url('user/default', ['controller' => 'auth', 'action' => 'twitter']) ?>">
                <i class="fa fa-twitter"></i>
            </a>
        <?php endif; ?>
    </p>
        <?php // $this->formInput($form->get('username')); ?>
        <input type="email" class="ember-view ember-text-field form-control login-input" id="inputEmail" name="<?= $form->get('email')->getName(); ?>"
               placeholder="<?= $form->get('email')->getLabel(); ?>">
        <div class="error-field error-form-message">
            <?= $this->formElementErrors($form->get('email')); ?>
        </div>

        <input type="password" class="ember-view ember-text-field form-control login-input" id="inputPassword"
               name="<?= $form->get('password')->getName(); ?>"
               placeholder="<?= $form->get('password')->getLabel(); ?>">
        <div class="error-field error-form-message">
            <?= $this->formElementErrors($form->get('password')); ?>
        </div>

<!--    <button class="btn btn-lg btn-primary btn-block btn-center" type="submit">Sign in</button>-->

        <input type="submit" name="submit" id="submitbutton" class="btn btn-lg btn-primary btn-block btn-center"
               value="<?= $form->get('submit')->getValue(); ?>">

        <a href="<?php echo $this->url('user/default', ['controller' => 'signup', 'action' => 'forgot-password']) ?>">
            Forgot your password?
        </a>

        <!--        --><?php //echo $this->formRow($form->get('submit')); ?>
        <?php echo $this->form()->closeTag(); ?>
</div>
<script>
    require(['starter']);
</script>
