<?php
$title = 'Login';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
/**
 * @var Zend/Form/Form $form
 */
$form = $this->form;
$form->setAttribute('action', $this->url('user/default', array('controller' => 'auth', 'action' => 'login')));
$form->prepare();
?>
<div class="container">
    <div class="row">
        <?php echo $this->form()->openTag($form); ?>
        <?php echo $this->formHidden($form->get('security')); ?>
        <div class="form-group">
            <label for="inputEmail" class="col-sm-2 control-label"><?= $form->get('email')->getLabel(); ?></label>

            <div class="col-sm-4">
                <?php // $this->formInput($form->get('username')); ?>
                <input type="email" class="form-control" id="inputEmail" name="<?= $form->get('email')->getName(); ?>"
                       placeholder="<?= $form->get('email')->getLabel(); ?>">
            </div>
            <?= $this->formElementErrors($form->get('email')); ?>
        </div>
        <div class="form-group">
            <label for="inputPassword" class="col-sm-2 control-label"><?= $form->get('password')->getLabel(); ?></label>

            <div class="col-sm-4">
                <input type="password" class="form-control" id="inputPassword"
                       name="<?= $form->get('password')->getName(); ?>"
                       placeholder="<?= $form->get('password')->getLabel(); ?>">
            </div>
            <?= $this->formElementErrors($form->get('password')); ?>
        </div>
        <div class="form-group">
            <div class="col-sm-2"></div>
            <div class="col-sm-4">
                <input type="submit" name="submit" id="submitbutton" class="btn btn-lg btn-primary btn-block"
                       value="<?= $form->get('submit')->getValue(); ?>">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-4 col-sm-offset-2">
                <a class="btn btn-primary col-sm-5"
                   href="<?php echo $this->url('user/default', ['controller' => 'auth', 'action' => 'twitter']) ?>">Twitter</a>
                <a class="btn btn-primary col-sm-5 col-sm-offset-2"
                   href="<?php echo $this->url('user/default', ['controller' => 'auth', 'action' => 'facebook']) ?>">Facebook</a>
            </div>
        </div>
        <!--        --><?php //echo $this->formRow($form->get('submit')); ?>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>