<?php echo $this->headLink()->prependStylesheet($this->basePath() . '/module/options/css/management.css'); ?>

<div class="container">

    <div class="text-center">
        <h2 class="create-label">Enter new password</h2>
        <?php $form->prepare(); ?>
        <?php echo $this->form()->openTag($form); ?>
        <?php echo $this->formHidden($form->get('security')); ?>
        <?php echo $this->formInput($form->get('password')); ?>
        <?php echo $this->formElementErrors($form->get('password')); ?>
        <?php echo $this->formInput($form->get('repeat-password')); ?>
        <?php echo $this->formElementErrors($form->get('repeat-password')); ?>
        <?php echo $this->formSubmit($form->get('submit')); ?>
        <?php echo $this->form()->closeTag(); ?>
    </div>

</div>
<script>
    require(['fury']);
</script>