<?php echo $this->headLink()->prependStylesheet($this->basePath() . '/module/options/css/management.css'); ?>

<div class="container">

    <div class="col-md-10">
        <h1 class="create-label">Recovery password</h1>
        <?php $form->prepare(); ?>
        <?php echo $this->form()->openTag($form); ?>
        <?php echo $this->formHidden($form->get('security')); ?>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('password')); ?>
            <div class="col-sm-10">
                <?php echo $this->formInput($form->get('password')); ?>
                <?php echo $this->formElementErrors($form->get('password')); ?>
            </div>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('repeat-password')); ?>
            <div class="col-sm-10">
                <?php echo $this->formInput($form->get('repeat-password')); ?>
                <?php echo $this->formElementErrors($form->get('repeat-password')); ?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-2">
            </div>
            <div class="col-sm-10">
                <?php echo $this->formSubmit($form->get('submit')); ?>
            </div>
        </div>

        <?php echo $this->form()->closeTag(); ?>
    </div>
    <div class="col-md-2">
    </div>
</div>
<script>
    require(['starter']);
</script>