<?php echo $this->headLink()->prependStylesheet($this->basePath() . '/module/options/css/management.css'); ?>

<div class="container">

    <div class="col-md-6">
        <h1 class="create-label">Create</h1>
        <?php $form->prepare(); ?>
        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('namespace')); ?>
            <div class="col-sm-10">
                <?php echo $this->formInput($form->get('namespace')
                    ->setValue(\Options\Entity\Options::NAMESPACE_DEFAULT)); ?>
                <?php echo $this->formElementErrors($form->get('namespace')); ?>
            </div>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('key')); ?>
            <div class="col-sm-10">
                <?php echo $this->formInput($form->get('key')); ?>
                <?php echo $this->formElementErrors($form->get('key')); ?>
            </div>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('value')); ?>
            <div class="col-sm-10">
                <?php echo $this->formInput($form->get('value')); ?>
                <?php echo $this->formElementErrors($form->get('value')); ?>
            </div>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('description')); ?>
            <div class="col-sm-10">
                <?php echo $this->formTextarea($form->get('description')); ?>
                <?php echo $this->formElementErrors($form->get('description')); ?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-2">
            </div>
            <div class="col-sm-10">
                <?php echo $this->formSubmit($form->get('submit')); ?>
            </div>
        </div>

        <?php echo $this->form()->closeTag(); ?>
    </div>
    <div class="col-md-6">
    </div>
</div>