<?php $escaper = new Zend\Escaper\Escaper('utf-8'); ?>

<h1>Option</h1>

<div class="row">
    <p>Namespace: <?php echo $escaper->escapeHtml($option->getNamespace()); ?></p>
    <p>Key: <?php echo $escaper->escapeHtml($option->getKey()); ?></p>
    <p>Value: <?php echo $escaper->escapeHtml($option->getValue()); ?></p>
    <p>Description: <?php echo $escaper->escapeHtml($option->getDescription()); ?></p>
    <p>Created: <?php echo $escaper->escapeHtml($option->getCreated()->format('Y-m-d H:i:s')); ?></p>
    <p>Updated: <?php echo $escaper->escapeHtml($option->getUpdated()->format('Y-m-d H:i:s')); ?></p>
</div>
