<div class="jumbotron">
    <h1>Option</h1>
</div>

<div class="row">
    <p>Namespace: <?php echo $option->getNamespace(); ?></p>
    <p>Key: <?php echo $option->getKey(); ?></p>
    <p>Value: <?php echo $option->getValue(); ?></p>
    <p>Description: <?php echo $option->getDescription(); ?></p>
    <p>Created: <?php echo $option->getCreated()->format('Y-m-d H:i:s'); ?></p>
    <p>Created: <?php echo $option->getCreated()->format('Y-m-d H:i:s'); ?></p>
</div>
