<div>
    <ul>
        <?php foreach ($imagesId as $imageId) { ?>
            <li><?= $imageId ?></li>
        <?php } ?>
    </ul>
</div>
<div>
    <ul>
        <?php foreach ($imagesUrl as $imageUrl) { ?>
            <li><?= $imageUrl ?></li>
        <?php } ?>
    </ul>
</div>
<div>
    <ul>
        <?php foreach ($imagesLocation as $imageLocation) { ?>
            <li><?= $imageLocation ?></li>
        <?php } ?>
    </ul>
</div>
<div>
    <ul>
        <?php foreach ($thumbsUrl as $thumbUrl) { ?>
            <li><?= $thumbUrl ?></li>
        <?php } ?>
    </ul>
</div>