<link href="module/comment/css/comment.css" rel="stylesheet">
<ul class="media">
    <li class="media-body">
            <h5 class="media-heading">
                <div class="col-sm-3">
                    <?php echo $this->escapeHtml(\Comment\Service\Comment::cutName($this->comment->getUser()->getDisplayName()))?>
                </div>
                <div class="col-sm-1"><i class="delimeter glyphicon glyphicon-asterisk"></i></div>
                <div class="col-sm-6">
                    <small><?= $this->comment->getCreated()->format('d-m-Y  h:m'); ?></small>;
                </div>
                <?php
                if (($this->comment->getUserId() === $this->identity()->getUserId() &&
                        $this->enabledCommentByComment) ||
                    $this->identity()->getUser()->getRole() === User\Entity\User::ROLE_ADMIN) : ?>
                    <a class="dialog"
                       href="<?php echo $this->url('comment/default', array(
                           'controller'=>'index',
                           'action' => 'edit',
                           'id' => $this->comment->getId()
                       )); ?>">
                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                    </a>
                    <a class="del-comment" href="<?php echo $this->url('comment/default', array(
                        'controller'=>'index',
                        'action' => 'delete',
                        'id' => $this->comment->getId()
                    )); ?>">
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                    </a>
                <?php endif; ?>
            </h5>
            <div class="comment-text form-control col-md-6">
                <?php echo $this->escapeHtml($this->comment->getComment()); ?>
            </div>
            <?php if ($this->enabledCommentByComment) : ?>
                <p>
                    <small><a href="<?=$this->url(
                                'comment/default',
                                ['controller' => 'index', 'action' => 'add'],
                                ['query' => ['entity' => 'comment', 'id' => $this->comment->getId()]]
                            )?>"
                            id="answer-button">
                            <span aria-hidden="true"></span>Answer
                        </a>
                    </small>
                </p>
            <?php endif; ?>
            <?php if (count($this->children) > 0) : ?>
                <?php echo $this->comment('comment/index/partial/comment.phtml', $this->children); ?>
            <?php endif; ?>
    </li>
</ul>
