<li class="media comment-body" data-id="<?= $this->comment->getId() ?>">
    <div class="media-body">
    <h5 class="media-heading row">
        <div class="col-sm-3" data-toggle="tooltip" data-placement="top" title="<?= $this->comment->getUser()->getDisplayName()?>"><?php echo $this->escapeHtml(\Comment\Service\Comment::cutName($this->comment->getUser()->getDisplayName()))?></div>
        <div class="col-sm-6">
            <small><?= $this->comment->getCreatedAt()->format('d-m-Y  H:m:s') ?></small>;
        </div>
        <?php if (($this->comment->getUserId() === $this->identity()->getUserId() && $this->enabledCommentByComment) || $this->identity()->getUser()->getRole() === User\Entity\User::ROLE_ADMIN) : ?>
        <div class="col-sm-3 text-right  edit-delete">
            <a class="edit-comment" data-ajax-method="" href="javascript:;">
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
            </a>
            <a class="del-comment confirm ajax" data-ajax-method="delete" href="<?php echo $this->url('comment/default', array('controller'=>'index', 'action' => 'delete', 'id' => $this->comment->getId())); ?>">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
            </a>
        </div>
        <?php endif; ?>
    </h5>
    <div class="comment-text form-control"><?php echo $this->escapeHtml($this->comment->getComment()); ?></div>
    <?php if ($this->enabledCommentByComment) : ?>
    <div class="answer-block"><small><a class="answer-button" href="javascript:;">Answer</a></small></div>
    <?php endif; ?>
    <?php if (count($this->children) > 0) : ?>
        <ul><?= $this->comment('comment/index/partial/comment.phtml', $this->children); ?></ul>
    <?php endif; ?>
    </div>
</li>
