<li class="media comment-body" data-id="<?= $this->comment->getId() ?>">
    <div class="media-body">
    <h5 class="media-heading row">
        <div class="col-sm-3" data-toggle="tooltip" data-placement="top" title="<?= $this->comment->getUser()->getDisplayName()?>"><?php echo $this->escapeHtml($this->cutString($this->comment->getUser()->getDisplayName(), 8, '...'))?></div>
        <div class="data-edit col-sm-9 text-right">
            <div class="data text-right">
                <small><?= $this->comment->getCreated()->format('d-m-Y  H:m:s') ?></small>
            </div>
            <?php if (($this->comment->getUserId() === $this->identity()->getUserId() && $this->enabledCommentByComment) || $this->identity()->getUser()->getRole() === User\Entity\User::ROLE_ADMIN) : ?>
            <div class="text-right  edit-delete">
                <a class="edit-comment" href="javascript:;">
                    <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                </a>
                <a class="del-comment confirm ajax" data-ajax-method="delete" href="<?php echo $this->url('comment/default', array('controller'=>'index', 'action' => 'delete', 'id' => $this->comment->getId())); ?>">
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                </a>
            </div>
            <?php endif; ?>
        </div>
    </h5>
    <div class="comment-text form-control"><?php echo $this->escapeHtml($this->comment->getComment()); ?></div>
    <?php if ($this->enabledCommentByComment) : ?>
        <div class="answer-block"><small><a class="answer-button" href="javascript:;">Answer</a></small></div>
    <?php endif; ?>
    <?php if (count($this->children) > 0) : ?>
        <ul><?= $this->comment('comment/index/partial/comment.phtml', $this->children); ?></ul>
    <?php endif; ?>
    </div>
</li>
