<?php
//$title = 'Add new comment';
//$this->headTitle($title);
?>
<?php
/**
 * @var Zend/Form/Form $form
 */
$form = $this->form;
$form->prepare();
?>
<div class="container">
    <h1><?php echo $this->escapeHtml($this->title); ?></h1>

    <div class="row">
        <form action="" method="post" class="form-horizontal" id="newCategory">
            <div class="form-group">
                <label for="inputComment" class="col-sm-2 control-label"><?= $form->get('comment')->getLabel(); ?></label>
                <div class="col-sm-4">
                    <?php echo $this->formTextarea($form->get('comment')); ?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-2"></div>
                <div class="col-sm-4">
                    <input type="submit" name="submit" class="form-control col-sm-4 btn btn-success" value="Save">
                </div>
            </div>
        </form>
    </div>
</div>