<?php
/**
 * @var Zend/Form/Form $form
 */
$form = $this->form;
$form->prepare();
?>
<div class="container">
    <h1><?php echo $this->escapeHtml($this->title); ?></h1>

    <div class="row">
        <form id="crudForm" method="post" class="form-horizontal">
            <div class="form-group">
                <label for="inputComment" class="col-sm-1 control-label"><?= $form->get('comment')->getLabel(); ?></label>
                <div class="col-sm-4">
                    <?php echo $this->formTextarea($form->get('comment')); ?>
                </div>
                <div class="col-sm-9 col-md-offset-2 error-field error-form-message">
                    <?= $this->formElementErrors($form->get('comment')); ?>
                </div>
            </div>
            <?php if (!$this->ajax): ?>
                <div class="form-group">
                    <div class="col-sm-5 col-sm-offset-">
                        <input type="submit" name="submit" class="form-control col-md-6 btn btn-success"
                               value="<?= $this->title == 'Edit comment' ? 'Save' : 'Add'; ?>">
                    </div>
                </div>
            <?php endif; ?>
        </form>
    </div>
</div>
<script>
    require(['starter']);
</script>
