<ul class="media">
    <li class="media">
        <div class="media-body">
            <h4 class="media-heading">
                <?php echo $this->escapeHtml($this->comment->getUser()->getDisplayName()); ?>
                <?php
                if ($this->comment->getUserId()===$this->identity()->getUserId()) : ?>
                    <a href="<?php echo $this->url('comment/default', array('controller'=>'index', 'action' => 'edit', 'id' => $this->comment->getId())); ?>">
                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                    </a>
                    <a href="<?php echo $this->url('comment/default', array('controller'=>'index', 'action' => 'delete', 'id' => $this->comment->getId())); ?>">
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                    </a>
                <?php endif; ?>
            </h4>
            <textarea class="form-control span6" disabled><?php echo $this->escapeHtml($this->comment->getComment()) ?></textarea>
            <?php
            if (count($this->childs) > 0) : ?>
                <?php echo $this->comment('comment/index/partial.phtml', $this->childs); ?>
            <?php endif; ?>
        </div>
    </li>
</ul>
