<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <?php require 'partial/header.phtml'; ?>
        <!-- CSS -->
        <link href="css/sb-admin.css" rel="stylesheet">
        <link href="font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body class="dashboard-body">
        <div id="wrapper">
            <?= $this->partial('layout/partial/flashmessenger.phtml') ?>
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <?= $this->partial('layout/partial/dashboard/nav-bar.phtml') ?>
            </nav>
            <div id="page-wrapper">
                <h1 class="page-header">
                    Dashboard <small>Statistics Overview</small>
                </h1>
                <div class="container-fluid">
                    <?php // echo $this->partial('layout/partial/dashboard/breadcrumbs.phtml)' ?>
                    <?= $this->content ?>
                </div>
            </div>
            <?= $this->partial('layout/partial/footer.phtml') ?>
            <?php echo $this->inlineScript() ?>
        </div>
    </body>
</html>
