<html lang="en">
    <?php require 'partial/header.phtml'; ?>
    <body>
    <?= $this->partial('layout/partial/flashmessenger.phtml') ?>
    <?php require 'partial/nav-bar.phtml'; ?>
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <?php require 'partial/dashboard/side-bar.phtml' ?>
            </div>
            <div class="col-lg-9">
                <?php require 'partial/dashboard/breadcrumbs.phtml' ?>
                <?= $this->content ?>
            </div>
        </div>
        <?php require 'partial/footer.phtml'; ?>
    </div>
    <?php echo $this->inlineScript() ?>
    </body>
</html>
