<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <?= $this->partial('layout/partial/header.phtml') ?>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <?= $this->partial('layout/partial/nav-bar.phtml') ?>
</nav>
<?= $this->partial('layout/partial/flashmessenger.phtml'); ?>
<div class="container">
    <?php echo $this->content; ?>
    <hr>
    <?= $this->partial('layout/partial/footer.phtml') ?>
</div>
<?php echo $this->inlineScript() ?>
</body>
</html>
