<html lang="en">
    <?php require 'partial/header.phtml'; ?>
    <body>
    <?php echo $this->partial('layout/partial/flashmessenger.phtml'); ?>
    <?php require 'partial/nav-bar.phtml'; ?>
    <div class="container">
        <?php echo $this->content; ?>
        <hr>
        <?php require 'partial/footer.phtml'; ?>
    </div> <!-- /container -->
    <?php echo $this->inlineScript() ?>
    </body>
</html>
