<?php echo $this->headLink()->prependStylesheet($this->basePath() . '/redactor/redactor.css'); ?>
<?php echo $this->headLink()->prependStylesheet($this->basePath() . '/module/options/css/management.css'); ?>

<div class="container">

    <div class="col-md-6">
        <h1 class="create-label">Edit</h1>
        <?php $form->prepare(); ?>
        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('title')); ?>
            <div class="col-sm-10">
                <?php echo $this->formInput($form->get('title')); ?>
                <?php echo $this->formElementErrors($form->get('title')); ?>
            </div>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('alias')); ?>
            <div class="col-sm-10">
                <?php echo $this->formInput($form->get('alias')); ?>
                <?php echo $this->formElementErrors($form->get('alias')); ?>
            </div>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('content')); ?>
            <div class="col-sm-10">
                <?php echo $this->formTextarea($form->get('content')); ?>
                <?php echo $this->formElementErrors($form->get('content')); ?>
            </div>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('keywords')); ?>
            <div class="col-sm-10">
                <?php echo $this->formInput($form->get('keywords')); ?>
                <?php echo $this->formElementErrors($form->get('keywords')); ?>
            </div>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('description')); ?>
            <div class="col-sm-10">
                <?php echo $this->formInput($form->get('description')); ?>
                <?php echo $this->formElementErrors($form->get('description')); ?>
            </div>
        </div>

        <div class="hidden-element">
            <?php echo $this->formHidden($form->get('id')); ?>
        </div>

        <div class="hidden-element">
            <?php echo $this->formHidden($form->get('userId')); ?>
        </div>

        <div class="form-group">
            <div class="col-sm-2">
            </div>
            <div class="col-sm-10">
                <?php echo $this->formSubmit($form->get('submit')); ?>
            </div>
        </div>

        <?php echo $this->form()->closeTag(); ?>
    </div>
    <div class="col-md-6">
    </div>
</div>

<script>
    require(['redactor'], function() {
        $('#content').redactor({
            scrollTarget: '.container',
            minHeight: 300, // pixels
            placeholder: 'Page content'
        });
    });
</script>
