<div class="site-index">
    <h1>Pages</h1>

    <p>
        <a href="<?php echo $this->url('pages/default',
            array(
                'controller' => 'management',
                'action' => 'create')
        );?>"
           class="btn btn-success">Create</a>
    </p>

    <table class="table table-hover grid">
        <thead>
        <tr>
            <th width="160px">Tile</th>
            <th>Description</th>
            <th width="160px">Created</th>
            <th width="160px">Updated</th>
            <th width="200px">Controls</th>
        </tr>
        </thead>
        <tbody>

        <?php if (empty($pages)): ?>
            <h3>There are no pages yet</h3>
        <?php endif; ?>

        <?php foreach ($pages as $page): ?>
            <tr>
                <td>
                    <a href="<?php echo $this->url('pages/default',
                        array(
                            'controller' => 'management',
                            'action' => 'view',
                            'id' => $page->getId())
                    ); ?>">
                        <?php echo $this->escapeHtml($page->getTitle()); ?>
                    </a>
                </td>
                <td><?php echo $this->escapeHtml($page->getDescription()); ?></td>
                <td><?php echo $this->escapeHtml($page->getCreated()->format('Y-m-d H:i:s')); ?></td>
                <td><?php echo $this->escapeHtml($page->getUpdated()->format('Y-m-d H:i:s')); ?></td>
                <td class="controls">
                    <a href="<?php echo $this->url('pages/default',
                        array(
                            'controller' => 'management',
                            'action' => 'edit',
                            'id' => $page->getId())
                    ); ?>"
                       class="btn btn-default btn-small">
                        Edit
                    </a>
                    <a href="<?php echo $this->url('pages/default',
                        array(
                            'controller' => 'management',
                            'action' => 'delete',
                            'id' => $page->getId())
                    ); ?>"
                       class="btn btn-danger btn-small">
                        Delete
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

</div>
