<h3 class="page-header">
    All Test Entities.
</h3>
<div data-spy="grid">
    <!--    FILTER-->
    <a class="btn btn-primary pull-left "
       href="<?= $this->url('comment/default', ['controller' => 'management', 'action' => 'create']) ?>">Create</a>
    <?= $this->filter($this->grid) ?>
    <!--    GRID-->
    <div class="grid">
        <table class="table table-fixed table-striped">
            <thead>
            <tr>
                <?php foreach ($this->grid->getColumns() as $alias => $column) : ?>
                    <?php if ($order = $this->grid->order($alias)) : ?>
                        <th><a href="<?= $order ?>"><?= $column ?></a></th>
                    <?php else : ?>
                        <th><?= $column ?></th>
                    <?php endif; ?>
                <?php endforeach; ?>
                <th width="96px"></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->grid->getData() as $row) : ?>
                <tr>
                    <?php foreach ($row as $key => $value) : ?>
                        <?php if ('visibleComment' === $key || 'enabledComment' === $key) {
                                if (true == $value) { ?>
                                    <td><i class="glyphicon glyphicon-ok"></i></td>
                                <?php } else { ?>
                                    <td><i class="glyphicon glyphicon-remove"></i></td>
                                <?php } ?>
                        <?php } else { ?>
                            <td><?= $value ?></td>
                        <?php } ?>
                    <?php endforeach; ?>
                    <td>
                        <a class="btn btn-primary btn-xs" href="<?=
                        $this->url('comment/default', ['controller' => 'management', 'action' => 'edit', 'id' => $row['id']])
                        ?>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                        <a class="btn btn-danger btn-xs del-entity" href="<?=
                        $this->url('comment/default', ['controller' => 'management', 'action' => 'delete', 'id' => $row['id']])
                        ?>"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <!--        PAGINATION-->
        <?= $this->pagination($this->grid, ['class' => ['pagination', 'pull-left']]) ?>
        <!--    LIMIT-->
        <?= $this->limit($this->grid, ['class' => 'pagination pagination-small pull-right']) ?>
    </div>
</div>
<script>
    require(['fury.grid', 'commentManagement', 'dashboard']);
</script>
