<?php echo $this->headLink()->prependStylesheet($this->basePath() . '/module/options/css/management.css'); ?>

<div class="container">

    <div class="col-md-10">
        <h2 class="create-label">Forgot password</h2>
        <?php $form->prepare(); ?>
        <?php echo $this->form()->openTag($form); ?>
        <?php echo $this->formHidden($form->get('security')); ?>
        <?php echo $this->formInput($form->get('email')); ?>
        <?php echo $this->formElementErrors($form->get('email')); ?>
        <?php echo $this->formSubmit($form->get('submit')); ?>
        <?php echo $this->form()->closeTag(); ?>
    </div>
    <div class="col-md-2">
    </div>
</div>
<script>
    require(['fury']);
</script>