<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">Home</a>
</div>
<div class="collapse navbar-collapse">
    <?php if ($this->identity()) : ?>
        <p class="navbar-text navbar-right">
            Logged in as <a href="<?php echo $this->url('user/default', ['controller' => 'profile']) ?>" class="on"><?= $this->identity()->getUser()->getEmail() ? $this->identity()->getUser()->getEmail() : $this->identity()->getUser()->getDisplayName(); ?></a>
            (<a href="<?php echo $this->url('user/default', ['controller' => 'auth', 'action' => 'logout']) ?>"><?php echo $this->translate('Logout') ?></a>)
        </p>
    <?php endif; ?>
</div>
<?= $this->partial('layout/partial/dashboard/side-bar.phtml') ?>
