<script>
    require(['jquery', 'bootstrap', 'modules/test/testApp', 'dashboard']);
</script>
<div ng-controller="testController">
    <div>
        <a class="btn btn-primary pull-left "
           href="<?= $this->url('test/default', ['controller' => 'management', 'action' => 'create-with-angular']) ?>">Create</a>
    </div>
    <div class="ng-scope">
        <div class="tab-content">
            <div class="tab-pane fade in active" id="users">
                <div class="row tab-wrapper row tab-wrapper-noscroll">
                    <form class="form-inline" role="form">
                            <select class="form-control" ng-model="filterField" ng-options="filter for filter in allowedFilters">
                            </select>
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Search" ng-model="searchString">
                            </div>
                            <button type="button" class="btn btn-default" ng-click="search()">Search</button>
                            <button type="button" class="btn btn-default" ng-click="searchString='';search();">Clear</button>
                    </form>
                    <div class="col-sm-8">
                        <div class="table-scroll">
                            <div>
                                <table class="users-grid table table-fixed  table-striped table-hover">
                                    <thead ng-show="filteredTests.length">
                                    <tr>
                                        <th class="col-md-1"><a ng-click="setOrder('test.id')">№</a></th>
                                        <th class="col-md-3">Email</th>
                                        <th class="col-md-3"><a ng-click="setOrder('test.name')">Name</a></th>
                                        <th class="col-md-1">Edit</th>
                                        <th class="col-md-1">Delete</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr ng-repeat="test in filteredTests  = testGrid">
                                        <td>
                                            <span ng-bind="test.id"></span>
                                        </td>
                                        <td>
                                            <span ng-bind="test.email"></span>
                                        </td>
                                        <td>
                                            <span ng-bind="test.name"></span>
                                        </td>
                                        <td>
                                            <a class="btn btn-primary btn-xs"
                                               href="<?=
                                               $this->url('test/default', ['controller' => 'management', 'action' => 'edit-with-angular'])
                                               ?>/{{test.id}}">
                                                <i class="fa fa-pencil"></i>
                                            </a>
                                        </td>
                                        <td>
                                            <a class="confirm btn btn-xs btn-danger ajax"
                                                href="<?=
                                                $this->url('test/default', ['controller' => 'management', 'action' => 'delete'])
                                                ?>/{{test.id}}">
                                                <i class="fa fa-trash-o"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                                <div class="btn-group" ng-show="totalPages > 1">
                                    <ul class="pagination pull-left">
                                        <button class="btn btn-default" type="button" ng-disabled="page == 1"
                                                ng-click="prev()">&laquo;</button>

                                            <li ng-repeat="p in getTimes(totalPages) track by $index">
                                                <button class="btn btn-default" type="button" ng-click="getTests($index)" ng-disabled="page === $index + 1">{{$index + 1}}</button>
                                            </li>

                                        <button class="btn btn-default" type="button" ng-disabled="page == totalPages"
                                                ng-click="next()">&raquo;</button>
                                    </ul>
                                </div>
                                <div class="btn-group col-lg-offset-1">
                                    <button class="btn btn-default" type="button" ng-disabled="limit == 1"
                                            ng-click="changeLimit(1)">1</button>
                                    <button class="btn btn-default" type="button" ng-disabled="limit == 5"
                                            ng-click="changeLimit(5)">5</button>
                                    <button class="btn btn-default" type="button" ng-disabled="limit == 10"
                                            ng-click="changeLimit(10)">10</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="spinner" style="display: none"></div>
                </div>
            </div>
        </div>
    </div>
</div>
