<div data-spy="grid">
    <!--    FILTER-->
    <a class="btn btn-primary pull-left "
       href="<?= $this->url('test/default', ['controller' => 'management', 'action' => 'create']) ?>">Create</a>
    <?php if (count($this->grid->getAllowedFilters())) : ?>
        <div class="col-md-6 pull-right">
            <form class="navbar-form filter-form pull-right">
                <div class="input-group">
                    <div class="input-group-btn grid-filter-search">
                        <button type="button" class="btn btn-default dropdown-toggle"
                                data-toggle="dropdown"><?=ucfirst(explode('.', current($this->grid->getAllowedFilters()))[1])?>
                            <span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <?php foreach ($this->grid->getAllowedFilters() as $filter) : ?>
                                <li><a href="javascript:;" data-filter="<?= $filter ?>"><?=ucfirst(explode('.', $filter)[1]) ?></a></li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                    <input class="grid-filter-search-input"
                           name="<?= 'filter-' . current($this->grid->getAllowedFilters()) ?>" type="hidden"/>
                    <input type="search" class="form-control"/>
                <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">Search</button>
                </span>
                </div>
            </form>
        </div>
    <?php endif; ?>
    <!--    GRID-->
    <div class="grid">
        <table class="table table-fixed table-striped">
            <thead>
            <tr>
                <?php foreach ($this->grid->getColumns() as $alias => $column) : ?>
                    <?php  if ($order = $this->grid->order($alias)) : ?>
                        <th><a href="<?= $order ?>"><?= $column ?></a></th>
                    <?php else : ?>
                        <th><?= $column ?></th>
                    <?php endif; ?>
                <?php endforeach; ?>
                <th width="96px"></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->grid->getData() as $row) : ?>
                <tr>
                    <?php foreach ($row as $key => $value) : ?>
                        <td><?= $value instanceof \DateTime ? $value->format('Y-m-d H:i:s') : $value ?></td>
                    <?php endforeach; ?>
                    <td>
                        <a class="btn btn-primary btn-xs" href="<?=
                        $this->url('test/default', ['controller' => 'management', 'action' => 'edit', 'id' => $row['id']])
                        ?>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                        <a class="btn btn-danger btn-xs" href="<?=
                        $this->url('test/default', ['controller' => 'management', 'action' => 'delete', 'id' => $row['id']])
                        ?>"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <!--        PAGINATION-->
        <?php if ($this->grid->totalPages() > 1) : ?>
            <ul class="pagination pull-left">
                <?php if ($prev = $this->grid->prev()) : ?>
                    <li><a href="<?= $this->grid->getUrl(['page' => $prev]); ?>">&laquo;</a></li>
                <?php else : ?>
                    <li class="disabled"><a href="javascript:;">&laquo;</a></li>
                <?php endif; ?>
                <?php for ($page = 1; $page <= $this->grid->totalPages(); $page++) : ?>
                    <li <?= ($page == $this->grid->getPage()) ? 'class="active"' : '' ?>>
                        <a href="<?= $this->grid->getUrl(['page' => $page]) ?>"><?= $page ?></a>
                    </li>
                <?php endfor; ?>
                <?php if ($next = $this->grid->next()) : ?>
                    <li><a href="<?= $this->grid->getUrl(['page' => $next]); ?>">&raquo;</a></li>
                <?php else : ?>
                    <li class="disabled"><a href="javascript:;">&raquo;</a></li>
                <?php endif; ?>
            </ul>
        <?php endif; ?>
        <!--    LIMIT-->
        <ul class="pagination pagination-small pull-right">
            <li class="disabled"><a href="javascript:;"><?= 'Limit' ?></a></li>
            <li <?= ($this->grid->getLimit() == 1) ? 'class="active"' : '' ?>><a
                    href="<?= $this->grid->getUrl(['limit' => 1]); ?>">1</a></li>
            <li <?= ($this->grid->getLimit() == 5) ? 'class="active"' : '' ?>><a
                    href="<?= $this->grid->getUrl(['limit' => 5]); ?>">5</a></li>
            <li <?= ($this->grid->getLimit() == 10) ? 'class="active"' : '' ?>><a
                    href="<?= $this->grid->getUrl(['limit' => 10]); ?>">10</a></li>
            <li <?= ($this->grid->getLimit() == 15) ? 'class="active"' : '' ?>><a
                    href="<?= $this->grid->getUrl(['limit' => 15]); ?>">15</a></li>
        </ul>
    </div>
</div>
<script>
    require(['starter.grid', 'dashboard']);
</script>
