<div data-spy="grid">
    <div class="grid">
        <div class="container">
            <div class="col-lg-12 form-center chart" id="registration-chart"></div>
            <h4>Last registered users</h4>
            <div class="col-lg-12 chart" id="last-registrations"></div>
<!--            --><?php //if ($this->users): ?>
<!--                <table class="table table-striped table-responsive table-hover">-->
<!--                    <thead>-->
<!--                    <tr>-->
<!--                        <th>Id</th>-->
<!--                        <th>E-Mail</th>-->
<!--                        <th>Displayed name</th>-->
<!--                        <th>Role</th>-->
<!--                        <th>Status</th>-->
<!--                        <th>Created at</th>-->
<!--                    </tr>-->
<!--                    </thead>-->
<!--                    --><?php ///** @var \User\Entity\User $user */ ?>
<!--                    --><?php //foreach ($this->users as $user): ?>
<!--                        <tr>-->
<!--                            <td>--><?php //echo $user->getId(); ?><!--</td>-->
<!--                            <td>--><?php //echo $user->getEmail(); ?><!--</td>-->
<!--                            <td>--><?php //echo $user->getDisplayName(); ?><!--</td>-->
<!--                            <td>--><?php //echo $user->getRole(); ?><!--</td>-->
<!--                            <td>--><?php //echo $user->getStatus(); ?><!--</td>-->
<!--                            <td>--><?php //echo $user->getCreated()->format('Y-m-d H:i:s'); ?><!--</td>-->
<!--                        </tr>-->
<!--                    --><?php //endforeach; ?>
<!--                </table>-->
<!--            --><?php //endif; ?>
        </div>
    </div>
</div>
<script>
    require(['dashboard', 'chart', 'statistic-table']);
</script>