<?php
/**
 * Created by PhpStorm.
 * User: babich
 * Date: 12/19/14
 * Time: 6:21 PM
 */
?>
<div class="modal fade" id="formModal" tabindex="-1" role="dialog" aria-labelledby="formModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title" id="formModalLabel"></h4>
            </div>
            <div class="modal-body" id="popupBody">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="close-form-button" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="submit-form-button">Save</button>
            </div>
        </div>
    </div>
</div>