<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sZFury%s'), '<span class="zf-green">', '</span>') ?></h1>
    <h2>You have successfully installed ZFury based on Zend Framework 2</h2>
</div>

<div class="panel panel-success">
    <div class="panel-heading">Login as administrator</div>
    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>Email</dt>
            <dd>admin@zfury.com</dd>
            <dt>Password</dt>
            <dd>admin</dd>
        </dl>
    </div>
</div>

<!--<div class="row">-->
<!--    <h2>What next?</h2>-->
<!--</div>-->
<script>
    require(['fury']);
</script>