<ul id="side-nav" class="nav navbar-nav side-nav">
    <?php foreach ($this->container as $pages) {
        $liLinks = [];
        $count = 0;
        foreach ($pages as $page) {
            $controller = $page->controller_namespace;
            $action = $page->action;
            if ($this->isAllowed("controller/$controller:$action") || $this->isAllowed("controller/$controller")) {
                $count++;
                $liLink = '<li>' . $this->navigation()->menu()->htmlify($page) . PHP_EOL . '</li>';
                array_push($liLinks, $liLink);
            }
        }

        if (0 !== $count) {
            echo '<li><a href="javascript:;" data-toggle="collapse" data-target="#' . $pages->label . '">' . $pages->label . '<i class="fa fa-fw fa-caret-down"></i></a>';
            echo '<ul id="' . $pages->label . '" class="collapse dashboard-menu">';
            for ($i = 0; $i < count($liLinks); $i++) {
                echo $liLinks[$i];
            }
            echo '</ul>';
            echo '</li>';
        }
    }
    ?>
</ul>
<script>require(['dashboard']);</script>