<?php
/** @var $user \User\Entity\User */
$user = $this->user;
?>

Hello User, To reset account password click on the following link or copy-paste it in your browser:

<a href="<?= $this->url('user/recover-password', ['hash' => $user->getConfirm()], ['force_canonical' => true]); ?>"
   title="Confirmation Link"><?= $this->url('user/recover-password', ['hash' => $user->getConfirm()], ['force_canonical' => true]); ?></a>
<script>
    require(['starter']);
</script>