<?php
/**@var $form Zend/Form */
$form = $this->form;
$ajax = $this->viewModel()->getCurrent()->terminate();
?>
    <div class="container">
        <h1>Edit user</h1>

        <div class="row">
            <form action="<?= $form->getAttribute('action') ?>" method="post"
                  class="form-horizontal <?= $ajax ? 'form-ajax' : '' ?>">
                <?php foreach ($this->form->getElements() as $element) : ?>
                    <?php
                    switch ($element) {
                        case $element instanceof Zend\Form\Element\Select :
                            $formElement = $this->formSelect($element);
                            break;
                        case $element instanceof Zend\Form\Element\Email :
                            $formElement = $this->formEmail($element);
                            break;
                        case $element instanceof Zend\Form\Element\Password :
                            $formElement = $this->formPassword($element);
                            break;
                        default :
                            $formElement = $this->formInput($element);
                            break;
                    }
                    ?>
                    <?php $element->getAttributes()['type'] == 'submit' ? $submit = true : $submit = false; ?>
                    <div class="form-group">
                        <?php if (!$submit): ?>
                            <?php if ($element->getAttributes()['type'] !== 'hidden'): ?>
                                <label for="<?= $element->getName(); ?>" class="col-sm-2 control-label">
                                    <?= $element->getLabel() ? $element->getLabel() : ucfirst($element->getName()); ?>
                                </label>
                            <?php endif; ?>
                            <div class="col-sm-4">
                                <?= $formElement; ?>
                                <div class="error-field error-form-message">
                                    <?= $this->formElementErrors($element); ?>
                                </div>
                            </div>
                        <?php elseif (!$ajax): ?>
                            <div class="col-sm-4 col-sm-offset-2">
                                <?= $formElement; ?>
                                <div class="error-field error-form-message">
                                    <?= $this->formElementErrors($element); ?>
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>
                <?php if (!$ajax): ?>
                    <div class="form-group">
                        <div class="col-sm-2"></div>
                        <div class="col-sm-4">
                            <input type="submit" name="submit" class="btn btn-lg btn-primary btn-block" value="Edit">
                        </div>
                    </div>
                <?php endif; ?>
            </form>
        </div>
    </div>
<?php if (!$ajax): ?>
    <script>
        require(['dashboard']);
    </script>
<?php endif; ?>