<script>
    require(['jquery', 'bootstrap', 'modules/user/userApp']);
</script>

<div ng-controller="userGridController" class="ng-scope">
    <div class="tab-content">
        <div class="tab-pane fade in active" id="users">
            <div class="row tab-wrapper row tab-wrapper-noscroll">
                <div class="input-group col-sm-8">
                    <input type="text" class="form-control col-md-12" placeholder="Поиск" ng-model="params.search" ng-keyup="search()">
                </div>
                <div class="col-sm-8">
                    <div class="table-scroll">
                        <div>
                            <table class="users-grid table table-fixed  table-striped table-hover">
                                <thead ng-show="filteredUsers.length">
                                <tr>
                                    <th class="col-md-1"><a ng-click="setOrder('id')">№</a></th>
                                    <th class="col-md-3"><a ng-click="setOrder('email')">Email</a></th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr ng-repeat="user in filteredUsers  = usersGrid ">
                                    <td>
                                        <span ng-bind="user.id"></span>
                                    </td>
                                    <td>
                                        <span ng-bind="user.email"></span>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                            <div class="btn-group" ng-show="filteredUsers.length">
                                <ul>
                                    <button class="btn btn-default" type="button" ng-disabled="page == 0"
                                            ng-click="getPage('prev')">PREV</button>
                                    {{page+1}} / {{gridPages}}
                                    <button type="button" class="btn btn-default" ng-click="getPage('next')"
                                            ng-disabled="page == gridPages-1">NEXT </button>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="spinner" style="display: none"></div>
                <div ng-view=""></div>
            </div>
        </div>
    </div>
</div>